/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice2nd.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/DarkOffice2nd.glb')

  const newMaterials = convertMaterialsToBasic(materials)
  
    // Fan reference
    const fanRef = useRef()
  
    // Rotate around Z-axis first. (Try Y or X if needed.)
    const localAxis = new THREE.Vector3(1, 0, 1)
  
    useFrame((state, delta) => {
      if (fanRef.current) {
        localAxis.normalize()
        // Rotate using the mesh's LOCAL axis (correct circular rotation)
        fanRef.current.rotateOnAxis(localAxis, -delta * 8)
      }
    })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Phone15_Baked.geometry} material={newMaterials['Phone15_Baked.001']} position={[0.95, 0.864, 0.706]} />
      <mesh geometry={nodes.Cup_of_coffee_Baked.geometry} material={newMaterials['Cup of coffee_Baked.001']} position={[0.793, 0.866, 0.778]} />
      <mesh geometry={nodes.Clock_Baked.geometry} material={newMaterials['Clock_Baked.001']} position={[0.562, 0.883, 0.769]} />
      <group position={[0.335, 0.955, 0.75]}>
        <mesh geometry={nodes.Plane001_0001.geometry} material={newMaterials['PictureFrame_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_1.geometry} material={newMaterials['Playing Cards Box_Baked']} />
        <mesh geometry={nodes.Plane001_0001_2.geometry} material={newMaterials['Eyeglasses_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_3.geometry} material={newMaterials['Book_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_4.geometry} material={newMaterials['Table Lamp_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_5.geometry} material={newMaterials['The_Hunter_And_His_Dog_vs_c_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_6.geometry} material={newMaterials.KeyboardLap_Baked} />
        <mesh geometry={nodes.Plane001_0001_7.geometry} material={newMaterials['Laptop.001_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_8.geometry} material={newMaterials['Laptop_Baked.002']} />
        <mesh geometry={nodes.Plane001_0001_9.geometry} material={newMaterials['GamingMouse_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_10.geometry} material={newMaterials['KeyBoard_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_11.geometry} material={newMaterials['Gaming Mousepad_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_12.geometry} material={newMaterials['Bottle_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_13.geometry} material={newMaterials['Monitor_Baked.002']} />
        <mesh geometry={nodes.Plane001_0001_14.geometry} material={newMaterials['DialPhone_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_15.geometry} material={newMaterials['DeskFan_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_16.geometry} material={newMaterials.vase_Baked} />
        <mesh geometry={nodes.Plane001_0001_17.geometry} material={newMaterials['henrikCarpet_Baked.003']} />
        <mesh geometry={nodes.Plane001_0001_18.geometry} material={newMaterials.GamingChairSupp_Baked} />
        <mesh geometry={nodes.Plane001_0001_19.geometry} material={newMaterials['ComputerCase_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_20.geometry} material={newMaterials['Cabinet_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_21.geometry} material={newMaterials['Safe_Baked.001']} />
        <mesh geometry={nodes.Plane001_0001_22.geometry} material={newMaterials.CornerTableBlack_Baked} />
      </group>

      <group position={[0.196, 0.857, 1.449]}>
        <mesh geometry={nodes.flowers_In_vaze001.geometry} material={newMaterials['PlantPot_Baked.001']} />
        <mesh geometry={nodes.flowers_In_vaze001_1.geometry} material={newMaterials['Leaves1_Baked.001']} />
        <mesh geometry={nodes.flowers_In_vaze001_2.geometry} material={newMaterials.Leaves2_Baked} />
      </group>

      <group ref={fanRef} position={[0.469, 1.008, 0.577]}>
        <mesh geometry={nodes.BladeFan_Baked001.geometry} material={newMaterials['DeskFan_Baked.001']} />
      </group>

    </group>
  )
}

useGLTF.preload('/DarkOffice2nd.glb')
