/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice4th.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/DarkOffice4th.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[-2.006, 0.552, -0.554]}>
        <mesh geometry={nodes['Obj3d66-395056-1-561002'].geometry} material={newMaterials['3rdSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_1'].geometry} material={newMaterials['2ndSetMergedBake_Baked.001']} />
        <mesh geometry={nodes['Obj3d66-395056-1-561002_2'].geometry} material={newMaterials['1stSetMergedBake_Baked']} />
      </group>
      <group position={[-1.956, 0.471, -2.056]} rotation={[0, -1.291, 0]} scale={1.249}>
        <mesh geometry={nodes.Plane001.geometry} material={newMaterials['CalatheaLeaves_Baked.002']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={newMaterials['CaletheaPot_Baked.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={newMaterials.ESPSnakebyte_Baked} />
        <mesh geometry={nodes.Plane001_3.geometry} material={newMaterials['Tree Pics Modern Wall Decoration_Baked.001']} />
      </group>
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes['737_39_02_W0001'].geometry} material={newMaterials.BlackCouch_Baked} />
        <mesh geometry={nodes['737_39_02_W0001_1'].geometry} material={newMaterials.Pillow3_Baked} />
        <mesh geometry={nodes['737_39_02_W0001_2'].geometry} material={newMaterials['Pillow4_Baked.001']} />
      </group>
      <group position={[-1.765, 0.209, 0.851]}>
        <mesh geometry={nodes.Plane020.geometry} material={newMaterials.Pillow1_Baked} />
        <mesh geometry={nodes.Plane020_1.geometry} material={newMaterials.Pillow2_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/DarkOffice4th.glb')
