/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice3rd.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/DarkOffice3rd.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <group position={[1.771, 2.285, -2.442]} scale={0.928}>
        <mesh geometry={nodes.Cube016.geometry} material={newMaterials['Horizon_Baked.001']} />
        <mesh geometry={nodes.Cube016_1.geometry} material={newMaterials['FinalFantasy_Baked.001']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={newMaterials['GodFall_Baked.001']} />
        <mesh geometry={nodes.Cube016_3.geometry} material={newMaterials['Farcry_Baked.001']} />
        <mesh geometry={nodes.Cube016_4.geometry} material={newMaterials['Re7_Baked.001']} />
        <mesh geometry={nodes.Cube016_5.geometry} material={newMaterials['Metro_Baked.002']} />
        <mesh geometry={nodes.Cube016_6.geometry} material={newMaterials['Creed_Baked.002']} />
        <mesh geometry={nodes.Cube016_7.geometry} material={newMaterials['Dirt5_Baked.002']} />
        <mesh geometry={nodes.Cube016_8.geometry} material={newMaterials['EldenRing_Baked.002']} />
        <mesh geometry={nodes.Cube016_9.geometry} material={newMaterials['Dyinglight_Baked.002']} />
      </group>
      <mesh geometry={nodes.Jewellery_Box_Baked.geometry} material={newMaterials['Jewellery Box_Baked.001']} position={[1.25, 2.199, -2.455]} />
      <mesh geometry={nodes.Ps5_Control_Baked.geometry} material={newMaterials['Ps5 Control_Baked.001']} position={[1.686, 1.604, -2.422]} />
      <mesh geometry={nodes.Painting_Baked.geometry} material={newMaterials['Painting_Baked.001']} position={[0.123, 1.87, -2.646]} />
      <mesh geometry={nodes.Outlets_Baked.geometry} material={newMaterials['Outlets_Baked.001']} position={[-1.822, 0.434, -2.636]} />
      <group position={[-1.637, 0.218, -2.386]}>
        <mesh geometry={nodes.Plane008.geometry} material={newMaterials['Charger_Baked.001']} />
        <mesh geometry={nodes.Plane008_1.geometry} material={newMaterials['Boot.R_Baked']} />
        <mesh geometry={nodes.Plane008_2.geometry} material={newMaterials['Boot.L_Baked']} />
        <mesh geometry={nodes.Plane008_3.geometry} material={newMaterials.CertificateFE_Baked} />
        <mesh geometry={nodes.Plane008_4.geometry} material={newMaterials['Basket Trophy_Baked.001']} />
        <mesh geometry={nodes.Plane008_5.geometry} material={newMaterials['Single Column Trophy_Baked.002']} />
        <mesh geometry={nodes.Plane008_6.geometry} material={newMaterials['Frog_Baked.001']} />
        <mesh geometry={nodes.Plane008_7.geometry} material={newMaterials['Typewriter_Baked.003']} />
        <mesh geometry={nodes.Plane008_8.geometry} material={newMaterials['Scale_Baked.003']} />
        <mesh geometry={nodes.Plane008_9.geometry} material={newMaterials['Wall Cabinet_Baked.002']} />
        <mesh geometry={nodes.Plane008_10.geometry} material={newMaterials['VinylSleeves_Baked.001']} />
        <mesh geometry={nodes.Plane008_11.geometry} material={newMaterials['AMDisk_Baked.001']} />
        <mesh geometry={nodes.Plane008_12.geometry} material={newMaterials['Speaker_Baked.001']} />
        <mesh geometry={nodes.Plane008_13.geometry} material={newMaterials['DVD-MCU-1_Iron Man_Baked']} />
        <mesh geometry={nodes.Plane008_14.geometry} material={newMaterials['DVD-MCU-2_The Incredible Hulk_Baked']} />
        <mesh geometry={nodes.Plane008_15.geometry} material={newMaterials['DVD-MCU-3_Iron Man 2_Baked']} />
        <mesh geometry={nodes.Plane008_16.geometry} material={newMaterials['DVD-MCU-4_Thor_Baked']} />
        <mesh geometry={nodes.Plane008_17.geometry} material={newMaterials['DVD-MCU-5_Captain America The First Avenger_Baked']} />
        <mesh geometry={nodes.Plane008_18.geometry} material={newMaterials['DVD-MCU-6_Marvels The Avengers_Baked.001']} />
        <mesh geometry={nodes.Plane008_19.geometry} material={newMaterials['Camera_Baked.001']} />
        <mesh geometry={nodes.Plane008_20.geometry} material={newMaterials['Vr Headset_Baked.001']} />
        <mesh geometry={nodes.Plane008_21.geometry} material={newMaterials['PS5_Baked.001']} />
        <mesh geometry={nodes.Plane008_22.geometry} material={newMaterials['AMAlbum_Baked.001']} />
        <mesh geometry={nodes.Plane008_23.geometry} material={newMaterials['Vinyl Player_Baked.001']} />
        <mesh geometry={nodes.Plane008_24.geometry} material={newMaterials['horse_statue_01_Baked.002']} />
        <mesh geometry={nodes.Plane008_25.geometry} material={newMaterials['Chess Trophy.001_Baked.001']} />
        <mesh geometry={nodes.Plane008_26.geometry} material={newMaterials['Majestic Trophy_Baked.001']} />
        <mesh geometry={nodes.Plane008_27.geometry} material={newMaterials.CertificatesBE_Baked} />
        <mesh geometry={nodes.Plane008_28.geometry} material={newMaterials.CertificatesPY_Baked} />
      </group>
      <mesh geometry={nodes.ShelvePots.geometry} material={newMaterials.textured_0} position={[0.104, 0.991, -2.49]} />
    </group>
  )
}

useGLTF.preload('/DarkOffice3rd.glb')
