/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice6th.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes } = useGLTF('/models/DarkOffice6th.glb')

  // Load the video texture
    const monitorVideo = useVideoTexture('/videos/darkroomvid.mp4', {
      crossOrigin: 'anonymous',
      muted: true,
      loop: true,
      autoplay: true,
      playsInline: true,
    })
    
    // Just incase video is flipped vertically (comment-out if not needed)
    monitorVideo.center.set(0.5, 0.5)
    monitorVideo.flipY = false        // ensure proper vertical orientation
  
    // Debugging logs
    useEffect(() => {
      if (!nodes.Monitor_Screen) {
        console.error('Monitor_Screen mesh not found in GLB!')
      } else {
        console.log('Monitor_Screen mesh found:', nodes.Monitor_Screen)
      }
  
      if (!monitorVideo) {
        console.error('Video texture not created!')
      } else {
        console.log('Video texture:', monitorVideo)
        console.log('Video readyState:', monitorVideo.image?.readyState)
        console.log('Video paused?', monitorVideo.image?.paused)
        console.log('Video width/height:', monitorVideo.image?.videoWidth, monitorVideo.image?.videoHeight)
      }
    }, [nodes, monitorVideo])

  return (
    <mesh 
      geometry={nodes.Monitor_Screen.geometry} 
      position={[1.352, 0.859, 0.289]} 
      {...props}
    > 
      <meshBasicMaterial
          map={monitorVideo}
          toneMapped={false}
      />
    </mesh>
  )
}

useGLTF.preload('/DarkOffice6th.glb')
