/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice1st.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/DarkOffice1st.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wall1k_Baked.geometry} material={newMaterials['Wall1k_Baked.006']} position={[0.001, 0.008, 0]} />
      <mesh geometry={nodes.Shepherd1k_Baked.geometry} material={newMaterials.Shepherd1k_Baked} position={[1.89, 0.633, -1.54]} />
      <mesh geometry={nodes.Bunny_Soft_Toy1k_Baked.geometry} material={newMaterials['Bunny Soft Toy1k_Baked']} position={[1.449, 0.312, -1.357]} />
      <group position={[1.795, 0.308, -1.476]}>
        <mesh geometry={nodes.Cylinder_Material001_0003.geometry} material={newMaterials['DogBed1k_Baked.001']} />
        <mesh geometry={nodes.Cylinder_Material001_0003_1.geometry} material={newMaterials.Dogtoys1k_Baked} />
      </group>
      <mesh geometry={nodes.BeanBags2.geometry} material={newMaterials['BeanBags.001_Baked']} position={[0.089, 0.481, -0.984]} />
      <mesh geometry={nodes.Floor2k_Baked.geometry} material={newMaterials['Floor2_Baked.004']} position={[0, -0.01, 0]} />
    </group>
  )
}

useGLTF.preload('/DarkOffice1st.glb')
