/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DarkOffice5th.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/DarkOffice5th.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  const seatRef = useRef();
  
    // Oscillate (wiper motion)
    useFrame((state) => {
      if (seatRef.current) {
        const t = state.clock.getElapsedTime();
        seatRef.current.rotation.y = Math.sin(t * 1.5) * 0.2;
        //             speed ↑       ^ amplitude (max angle)
      }
    });

  return (
    <group {...props} dispose={null}>
      <mesh 
        ref={seatRef}
        geometry={nodes.GamingChairSeat_Baked.geometry} 
        material={newMaterials['GamingChairSeat_Baked.001']} 
        position={[1.239, 0.132, 1.294]} 
      />
    </group>
  )
}

useGLTF.preload('/DarkOffice5th.glb')
