/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice7th.glb 
*/

import React from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes } = useGLTF('/models/LightOffice7th.glb')

  // Load the video texture
      const monitorVideo = useVideoTexture('/videos/lightroomvid.mp4', {
        crossOrigin: 'anonymous',
        muted: true,
        loop: true,
        autoplay: true,
        playsInline: true,
      })
  
    // Just incase video is flipped vertically (comment-out if not needed)
    monitorVideo.center.set(0.5, 0.5)
    monitorVideo.flipY = false        // ensure proper vertical orientation
    
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MonitorScreen.geometry} material={nodes.MonitorScreen.material} position={[1.192, 1.027, -28.409]} >
        <meshBasicMaterial
          map={monitorVideo}
          toneMapped={false}
      />
      </mesh>
    </group>
  )
}

useGLTF.preload('/LightOffice7th.glb')
