/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice6th.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice6th.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <group position={[-2.294, 0.498, -28.097]}>
        <mesh geometry={nodes.Object_0033.geometry} material={newMaterials['Canvas_Baked.001']} />
        <mesh geometry={nodes.Object_0033_1.geometry} material={newMaterials['Canvas painting_Baked.001']} />
        <mesh geometry={nodes.Object_0033_2.geometry} material={newMaterials['Easel.001_Baked.001']} />
        <mesh geometry={nodes.Object_0033_3.geometry} material={newMaterials['Saoirse_Baked.001']} />
        <mesh geometry={nodes.Object_0033_4.geometry} material={newMaterials['Paintbrushes_Baked.001']} />
        <mesh geometry={nodes.Object_0033_5.geometry} material={newMaterials['Palette_Baked.001']} />
        <mesh geometry={nodes.Object_0033_6.geometry} material={newMaterials['Stool_Baked.001']} />
      </group>
      <mesh geometry={nodes.CornerPlant2_Baked.geometry} material={newMaterials['CornerPlant2_Baked.001']} position={[-1.988, 0.235, -27.618]} />
      <mesh geometry={nodes.CornerPlant2pot_Baked.geometry} material={newMaterials['CornerPlant2pot_Baked.001']} position={[-1.988, 0.111, -27.618]} />
      <mesh geometry={nodes.Round_embossed_flower_carpet_Baked.geometry} material={newMaterials['Round embossed flower carpet_Baked.001']} position={[-0.818, 0.132, -28.171]} />
      <mesh geometry={nodes.Sankofa_Baked.geometry} material={newMaterials.Sankofa_Baked} position={[-0.964, 0.141, -29.846]} />
      <mesh geometry={nodes.PillowBasket_Baked.geometry} material={newMaterials['PillowBasket_Baked.001']} position={[-0.047, 0.265, -30.906]} />
      <mesh geometry={nodes.Rattan_Knot_Chair001_Baked001.geometry} material={newMaterials['Rattan Knot Chair.001_Baked.001']} position={[-0.376, 0.377, -28.874]} rotation={[0, -1.339, 0]} />
      <mesh geometry={nodes.peau_de_vache_Baked.geometry} material={newMaterials['peau de vache_Baked']} position={[-0.841, 0.142, -29.881]} rotation={[Math.PI, -1.484, Math.PI]} scale={1.032} />
    </group>
  )
}

useGLTF.preload('/LightOffice6th.glb')
