/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice3rd.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice3rd.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WindowFrame_Baked.geometry} material={newMaterials.WindowFrame_Baked} position={[1.121, 1.444, -32.735]} />
      <mesh geometry={nodes.WallCabinet_Baked.geometry} material={newMaterials['WallCabinet_Baked.002']} position={[-2.571, 0.359, -29.326]} />
      <group position={[-2.394, 2.375, -27.952]}>
        <mesh geometry={nodes.Circle006.geometry} material={newMaterials['WallClock_Baked.001']} />
        <mesh geometry={nodes.Circle006_1.geometry} material={newMaterials['StrawhatNR_Baked.001']} />
        <mesh geometry={nodes.Circle006_2.geometry} material={newMaterials['Wallplates_Baked.001']} />
        <mesh geometry={nodes.Circle006_3.geometry} material={newMaterials['VividBoho_Baked.001']} />
        <mesh geometry={nodes.Circle006_4.geometry} material={newMaterials.WallArt1_Baked} />
        <mesh geometry={nodes.Circle006_5.geometry} material={newMaterials['WallArt2_Baked.001']} />
        <mesh geometry={nodes.Circle006_6.geometry} material={newMaterials.Botanicboho_Baked} />
        <mesh geometry={nodes.Circle006_7.geometry} material={newMaterials.MountainBoho_Baked} />
        <mesh geometry={nodes.Circle006_8.geometry} material={newMaterials.LunarBoho_Baked} />
        <mesh geometry={nodes.Circle006_9.geometry} material={newMaterials['WallPlate2.002_Baked.001']} />
        <mesh geometry={nodes.Circle006_10.geometry} material={newMaterials['Strawhat_Baked.001']} />
        <mesh geometry={nodes.Circle006_11.geometry} material={newMaterials['DreamCatcher1_Baked.001']} />
        <mesh geometry={nodes.Circle006_12.geometry} material={newMaterials['UltraDreamCatcher_Baked.001']} />
        <mesh geometry={nodes.Circle006_13.geometry} material={newMaterials['Macrame2_Baked.001']} />
        <mesh geometry={nodes.Circle006_14.geometry} material={newMaterials.Macrame1_Baked} />
        <mesh geometry={nodes.Circle006_15.geometry} material={newMaterials['MacrameWood2_Baked.001']} />
        <mesh geometry={nodes.Circle006_16.geometry} material={newMaterials['Hand made clay vase.001_Baked']} />
        <mesh geometry={nodes.Circle006_17.geometry} material={newMaterials['ShelvePlant3_Baked.001']} />
        <mesh geometry={nodes.Circle006_18.geometry} material={newMaterials.StrawVase_Baked} />
        <mesh geometry={nodes.Circle006_19.geometry} material={newMaterials['ShelvePlant1Pot_Baked.001']} />
        <mesh geometry={nodes.Circle006_20.geometry} material={newMaterials['ShelvePlant1_Baked.001']} />
        <mesh geometry={nodes.Circle006_21.geometry} material={newMaterials['ShelvesRight.001_Baked']} />
      </group>
      <group position={[-1.46, 2.501, -32.372]}>
        <mesh geometry={nodes.Maillage014.geometry} material={newMaterials['basilPot_Baked.001']} />
        <mesh geometry={nodes.Maillage014_1.geometry} material={newMaterials['basil_Baked.001']} />
      </group>
      <group position={[-1.161, 1.374, -32.393]}>
        <mesh geometry={nodes.Plane041.geometry} material={newMaterials['BookshelfPlantPot_Baked.001']} />
        <mesh geometry={nodes.Plane041_1.geometry} material={newMaterials['BookshelfPlant_Baked.001']} />
      </group>
      <mesh geometry={nodes.MacrameWood_Baked.geometry} material={newMaterials['MacrameWood_Baked.001']} position={[-2.377, 1.644, -31.233]} />
    </group>
  )
}

useGLTF.preload('/LightOffice3rd.glb')
