/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice1st.glb 
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice1st.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  // Fan reference
      const fanRef = useRef()
    
      // Rotate around Z-axis first. (Try Y or X if needed.)
      const localAxis = new THREE.Vector3(1, 0, 1)
    
      useFrame((state, delta) => {
        if (fanRef.current) {
          localAxis.normalize()
          // Rotate using the mesh's LOCAL axis (correct circular rotation)
          fanRef.current.rotateOnAxis(localAxis, delta * 70)
        }
      })

  return (
    <group {...props} dispose={null}>
      <group position={[2.122, 0.068, -28.172]}>
        <mesh geometry={nodes.Cube028.geometry} material={newMaterials['Floor_Baked.002']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={newMaterials['Walls_Baked.002']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={newMaterials['Antler trophy display_Baked.001']} />
      </group>
      <mesh geometry={nodes.BackdropLight_Baked.geometry} material={newMaterials['BackdropLight_Baked.010']} position={[0, -0.01, -29.998]} />
      <mesh geometry={nodes.RattanTrashcan_Baked.geometry} material={newMaterials['RattanTrashcan_Baked.001']} position={[1.605, 0.131, -27.725]} />
      <mesh geometry={nodes.LAMP_SHADE_GRAY_Baked.geometry} material={newMaterials['LAMP_SHADE_GRAY_Baked.001']} position={[0.646, 0.783, -27.997]} />
      <group position={[1.717, 0.12, -28.98]}>
        <mesh geometry={nodes.Cube022.geometry} material={newMaterials['Desk Top_Baked']} />
        <mesh geometry={nodes.Cube022_1.geometry} material={newMaterials['RattanCompchair_Baked.001']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={newMaterials['Slippers_Baked.001']} />
        <mesh geometry={nodes.Cube022_3.geometry} material={newMaterials['Iphone_Baked.001']} />
      </group>
      <mesh geometry={nodes.CottonVase_Baked.geometry} material={newMaterials['CottonVase_Baked.001']} position={[1.093, 0.72, -27.974]} />
      <group position={[1.469, 0.727, -29.325]}>
        <mesh geometry={nodes.Plane024.geometry} material={newMaterials['Laptop_Baked.001']} />
        <mesh geometry={nodes.Plane024_1.geometry} material={newMaterials['LaptopScreen_Baked.002']} />
      </group>
      <mesh geometry={nodes.Decorative_vase_with_branches001_Baked.geometry} material={newMaterials['Decorative vase with branches.001_Baked.001']} position={[1.133, 0.981, -29.361]} />
      <mesh geometry={nodes.Tulips_Baked.geometry} material={newMaterials['Tulips_Baked.001']} position={[1.386, 0.835, -29.439]} />
      <group position={[1.334, 0.771, -28.348]}>
        <mesh geometry={nodes.Circle005.geometry} material={newMaterials['WoodCoaster.011_Baked.001']} />
        <mesh geometry={nodes.Circle005_1.geometry} material={newMaterials['Coffee mug n5_Baked.001']} />
        <mesh geometry={nodes.Circle005_2.geometry} material={newMaterials['Pidgey_Baked.001']} />
        <mesh geometry={nodes.Circle005_3.geometry} material={newMaterials['Mouse_Baked.001']} />
        <mesh geometry={nodes.Circle005_4.geometry} material={newMaterials['Monitor_Baked.001']} />
        <mesh geometry={nodes.Circle005_5.geometry} material={newMaterials['CatLamp_Baked.001']} />
        <mesh geometry={nodes.Circle005_6.geometry} material={newMaterials['Keyboard_Baked.001']} />
        <mesh geometry={nodes.Circle005_7.geometry} material={newMaterials['PencilHolder_Baked.001']} />
        <mesh geometry={nodes.Circle005_8.geometry} material={newMaterials['DeskClock_Baked.001']} />
        <mesh geometry={nodes.Circle005_9.geometry} material={newMaterials.Fan_Baked} />
        <mesh geometry={nodes.Circle005_10.geometry} material={newMaterials['DialPhone_Baked.001']} />
        <mesh geometry={nodes.Circle005_11.geometry} material={newMaterials['Tablet_blinn2_0_Baked.001']} />
        <mesh geometry={nodes.Circle005_12.geometry} material={newMaterials['NotebookPen_Baked.001']} />
      </group>
      <mesh geometry={nodes.BinderStacks_Baked.geometry} material={newMaterials['BinderStacks_Baked.001']} position={[2.296, 0.605, -29.329]} />
      <mesh geometry={nodes.MousePad_Baked.geometry} material={newMaterials['MousePad_Baked.004']} position={[1.499, 0.721, -28.525]} />

      <mesh ref={fanRef} geometry={nodes.FanBlade.geometry} material={newMaterials.Fan_Baked} position={[1.595, 0.818, -29.457]} />
    </group>
  )
}

useGLTF.preload('/LightOffice1st.glb')
