/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice2nd.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice2nd.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Long_curtain_Baked.geometry} material={newMaterials['Long curtain_Baked.001']} position={[1.215, 2.134, -32.508]} />
      <mesh geometry={nodes.Kilim_carpet_Baked.geometry} material={newMaterials['Kilim carpet_Baked.001']} position={[1.157, 0.133, -30.827]} />
      <group position={[1.158, 0.218, -30.705]}>
        <mesh geometry={nodes['3DModel_LowPoly001'].geometry} material={newMaterials['Hopi_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_1'].geometry} material={newMaterials['wicker_basket_01_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_2'].geometry} material={newMaterials['Minimalist_Coffee_Table_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_3'].geometry} material={newMaterials['Ceramic and golden vase_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_4'].geometry} material={newMaterials['Ceramic Pampass_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_5'].geometry} material={newMaterials['PampassGrass_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_6'].geometry} material={newMaterials['Magazine2_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_7'].geometry} material={newMaterials['Magazines_Baked.001']} />
        <mesh geometry={nodes['3DModel_LowPoly001_8'].geometry} material={newMaterials['Folded garment stack_Baked']} />
      </group>
      <mesh geometry={nodes.PlasticBox_Baked.geometry} material={newMaterials['PlasticBox_Baked.001']} position={[1.287, 0.227, -30.716]} />
      <group position={[0.621, 0.672, -32.092]}>
        <mesh geometry={nodes.Malla009.geometry} material={newMaterials['WhiteSofa_Baked.002']} />
        <mesh geometry={nodes.Malla009_1.geometry} material={newMaterials['PillowSofa1_Baked.002']} />
      </group>
      <mesh geometry={nodes.ArmRestBlanket_Baked.geometry} material={newMaterials['ArmRestBlanket_Baked.002']} position={[0.32, 0.602, -31.843]} />
      <mesh geometry={nodes.LovePillow003_Baked.geometry} material={newMaterials['LovePillow.003_Baked.002']} position={[0.728, 0.583, -31.908]} />
      <mesh geometry={nodes.Almofada_Pontilhado_Bege_Baked.geometry} material={newMaterials['Almofada Pontilhado Bege_Baked.001']} position={[0.983, 0.697, -32.166]} />
      <group position={[0.983, 0.545, -31.863]}>
        <mesh geometry={nodes.swearer_FIX004.geometry} material={newMaterials['sweater_FIX_Baked.002']} />
        <mesh geometry={nodes.swearer_FIX004_1.geometry} material={newMaterials['Round Pillow_Baked.002']} />
        <mesh geometry={nodes.swearer_FIX004_2.geometry} material={newMaterials['Pattern cushion-D_Baked.002']} />
        <mesh geometry={nodes.swearer_FIX004_3.geometry} material={newMaterials['Linen rustic pillow-02_Baked.002']} />
      </group>
      <mesh geometry={nodes.FoldBlanket_Baked.geometry} material={newMaterials['FoldBlanket_Baked.002']} position={[1.221, 0.525, -31.964]} />
      <mesh geometry={nodes.PillowSofa2_Baked.geometry} material={newMaterials['PillowSofa2_Baked.002']} position={[0.621, 0.672, -32.092]} />
      <mesh geometry={nodes.ChivePlant_Baked.geometry} material={newMaterials.ChivePlant_Baked} position={[0.626, 0.778, -32.607]} rotation={[Math.PI, 0, Math.PI]} scale={[1.534, 1.06, 1.596]} />
      <group position={[2.414, 0.132, -32.22]}>
        <mesh geometry={nodes.pot002.geometry} material={newMaterials['Big Monstera plant_Baked.001']} />
        <mesh geometry={nodes.pot002_1.geometry} material={newMaterials['plant pot_Baked']} />
        <mesh geometry={nodes.pot002_2.geometry} material={newMaterials.Pot_Baked} />
      </group>
      <group position={[2.725, 0.318, -31.906]}>
        <mesh geometry={nodes.Mesh008.geometry} material={newMaterials['SmallCouchPlant_Baked.001']} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={newMaterials['PlantCouch_Baked.001']} />
        <mesh geometry={nodes.Mesh008_2.geometry} material={newMaterials['Tulips_Baked.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/LightOffice2nd.glb')
