/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice4th.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice4th.glb')

  const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <group position={[-2.571, 2.264, -29.359]}>
        <mesh geometry={nodes.Cube045.geometry} material={newMaterials['Shelves_Baked.003']} />
        <mesh geometry={nodes.Cube045_1.geometry} material={newMaterials['BornToDie_Baked.001']} />
        <mesh geometry={nodes.Cube045_2.geometry} material={newMaterials['VinylStack3_Baked.001']} />
        <mesh geometry={nodes.Cube045_3.geometry} material={newMaterials['VinylStack_Baked.001']} />
        <mesh geometry={nodes.Cube045_4.geometry} material={newMaterials['ToyPlane_Baked.001']} />
        <mesh geometry={nodes.Cube045_5.geometry} material={newMaterials.UpBooks_Baked} />
        <mesh geometry={nodes.Cube045_6.geometry} material={newMaterials.BookStack3_Baked} />
        <mesh geometry={nodes.Cube045_7.geometry} material={newMaterials.Magz_Sub_Baked} />
        <mesh geometry={nodes.Cube045_8.geometry} material={newMaterials['White vase.001_Baked.001']} />
        <mesh geometry={nodes.Cube045_9.geometry} material={newMaterials['ShelfBasket_Baked.001']} />
        <mesh geometry={nodes.Cube045_10.geometry} material={newMaterials.Photography_Baked} />
        <mesh geometry={nodes.Cube045_11.geometry} material={newMaterials.Bookstack6_Baked} />
        <mesh geometry={nodes.Cube045_12.geometry} material={newMaterials['WoodenBox_Baked.001']} />
        <mesh geometry={nodes.Cube045_13.geometry} material={newMaterials.BookStack1_Baked} />
        <mesh geometry={nodes.Cube045_14.geometry} material={newMaterials.Bookstack7_Baked} />
        <mesh geometry={nodes.Cube045_15.geometry} material={newMaterials.BookStack2_Baked} />
        <mesh geometry={nodes.Cube045_16.geometry} material={newMaterials.BookStack4_Baked} />
        <mesh geometry={nodes.Cube045_17.geometry} material={newMaterials.Bookstack5_Baked} />
        <mesh geometry={nodes.Cube045_18.geometry} material={newMaterials['VinylStack2_Baked.001']} />
      </group>
      <group position={[-2.23, 2.22, -32.362]}>
        <mesh geometry={nodes.Plano004.geometry} material={newMaterials['Asplenium Nidu Pot_Baked']} />
        <mesh geometry={nodes.Plano004_1.geometry} material={newMaterials['Asplenium Nidu Plant.001_Baked.001']} />
      </group>
      <group position={[-2.094, 0.381, -31.283]}>
        <mesh geometry={nodes.Maillage015.geometry} material={newMaterials['Stack of books.002_Baked.001']} />
        <mesh geometry={nodes.Maillage015_1.geometry} material={newMaterials['Stack of books_Baked']} />
      </group>
      <mesh geometry={nodes.ChivePlant_Baked001.geometry} material={newMaterials.ChivePlant_Baked} position={[-2.208, 1.39, -32.336]} rotation={[Math.PI, 0, Math.PI]} scale={[1.534, 1.06, 1.596]} />
      <mesh geometry={nodes.CornerShelf_Baked.geometry} material={newMaterials['CornerShelf_Baked.002']} position={[-2.271, 1.532, -32.398]} />
    </group>
  )
}

useGLTF.preload('/LightOffice4th.glb')
