/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LightOffice5th.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/LightOffice5th.glb')

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CatCushion_Baked.geometry} material={newMaterials['CatCushion_Baked.001']} position={[-1.07, 0.16, -32.191]} />
      <group position={[-2.162, 0.132, -32.203]}>
        <mesh geometry={nodes.Circle011.geometry} material={newMaterials['ModularPot_Baked.001']} />
        <mesh geometry={nodes.Circle011_1.geometry} material={newMaterials['FEUILLE_Baked.001']} />
      </group>
      <group position={[-1.706, 0.231, -32.202]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={newMaterials['Vase_Baked.001']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={newMaterials['Fiber stick_Baked.001']} />
      </group>
      <mesh geometry={nodes.Leaves_Baked.geometry} material={newMaterials['Leaves_Baked.001']} position={[-1.737, 0.757, -32.231]} />
      <group position={[-0.644, 0.14, -31.919]} rotation={[0, -1.571, 0]} scale={[0.752, 0.713, 0.752]}>
        <mesh geometry={nodes.Plane044.geometry} material={newMaterials['Tapis 22_Baked']} />
        <mesh geometry={nodes.Plane044_1.geometry} material={newMaterials['PetBowl_Baked.001']} />
        <mesh geometry={nodes.Plane044_2.geometry} material={newMaterials['CattoBed_Baked.001']} />
        <mesh geometry={nodes.Plane044_3.geometry} material={newMaterials['CatTree_Baked.001']} />
        <mesh geometry={nodes.Plane044_4.geometry} material={newMaterials['Catto_Baked.001']} />
        <mesh geometry={nodes.Plane044_5.geometry} material={newMaterials['CatHouse_Baked.001']} />
        <mesh geometry={nodes.Plane044_6.geometry} material={newMaterials['CatScratch_Baked.001']} />
        <mesh geometry={nodes.Plane044_7.geometry} material={newMaterials.WhiteGuitar_Baked} />
        <mesh geometry={nodes.Plane044_8.geometry} material={newMaterials['Boholshit_Baked.003']} />
        <mesh geometry={nodes.Plane044_9.geometry} material={newMaterials['VinylPlayer_Baked.002']} />
        <mesh geometry={nodes.Plane044_10.geometry} material={newMaterials['Bambino_Baked.002']} />
        <mesh geometry={nodes.Plane044_11.geometry} material={newMaterials['Radio_Baked.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/LightOffice5th.glb')
